// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignupController;

namespace SignupController.Migrations
{
    [DbContext(typeof(UserNContext))]
    [Migration("20200319110111_Updated_Name")]
    partial class Updated_Name
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("SignupController.UserNDB", b =>
                {
                    b.Property<int>("UserNId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("UserNId");

                    b.ToTable("UserNs");
                });
#pragma warning restore 612, 618
        }
    }
}
